// GENERATED from 0001_domain_v1.sql, 0002_state_taxonomy.sql, 0003_rbac_tenant_guards.sql, 0004_outreach_policy.sql, 0005_core_api_persistence.sql, 0006_auth_v1.sql, 0007_auth_audit.sql by scripts/generate-drizzle-schema.mjs.
// SQL migrations remain canonical for checks and indexes; do not edit this file manually.
import { boolean, bigint, char, customType, foreignKey, integer, jsonb, numeric, pgSchema, primaryKey, smallint, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';

const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({ dataType: () => 'bytea' });
export const rhia = pgSchema('rhia');

export const schemaMigration = rhia.table("schema_migration", {
  version: text("version").primaryKey(),
  appliedAt: timestamp("applied_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  checksumSha256: char("checksum_sha256", { length: 64 }).notNull(),
}, (table) => [
]);

export const organization = rhia.table("organization", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  defaultLocale: text("default_locale").default("es-EC").notNull(),
  defaultTimezone: text("default_timezone").default("America/Guayaquil").notNull(),
  active: boolean("active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const appUser = rhia.table("app_user", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  email: text("email").notNull(),
  displayName: text("display_name").notNull(),
  status: text("status").default("ACTIVE").notNull(),
  authProvider: text("auth_provider").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
]);

export const role = rhia.table("role", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  key: text("key").notNull(),
  name: text("name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("role_generated_uq_0").on(table.organizationId, table.key),
]);

export const permission = rhia.table("permission", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull().unique(),
  description: text("description").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const userRole = rhia.table("user_role", {
  userId: uuid("user_id").notNull().references(() => appUser.id),
  roleId: uuid("role_id").notNull().references(() => role.id),
  grantedAt: timestamp("granted_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  grantedByUserId: uuid("granted_by_user_id").references(() => appUser.id),
}, (table) => [
  primaryKey({ columns: [table.userId, table.roleId] }),
]);

export const rolePermission = rhia.table("role_permission", {
  roleId: uuid("role_id").notNull().references(() => role.id),
  permissionId: uuid("permission_id").notNull().references(() => permission.id),
  grantedAt: timestamp("granted_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.roleId, table.permissionId] }),
]);

export const agentDefinition = rhia.table("agent_definition", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull(),
  name: text("name").notNull(),
  version: text("version").notNull(),
  purpose: text("purpose").notNull(),
  status: text("status").default("ACTIVE").notNull(),
  defaultPolicyId: uuid("default_policy_id"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("agent_definition_generated_uq_0").on(table.key, table.version),
]);

export const agentInstance = rhia.table("agent_instance", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  agentDefinitionId: uuid("agent_definition_id").notNull().references(() => agentDefinition.id),
  configuration: jsonb("configuration").default({}).notNull(),
  status: text("status").default("INACTIVE").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const capability = rhia.table("capability", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull().unique(),
  riskLevel: text("risk_level").notNull(),
  requiresApprovalDefault: boolean("requires_approval_default").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const agentCapability = rhia.table("agent_capability", {
  agentDefinitionId: uuid("agent_definition_id").notNull().references(() => agentDefinition.id),
  capabilityId: uuid("capability_id").notNull().references(() => capability.id),
  policyOverrides: jsonb("policy_overrides").default({}).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.agentDefinitionId, table.capabilityId] }),
]);

export const job = rhia.table("job", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  agentInstanceId: uuid("agent_instance_id").references(() => agentInstance.id),
  jobType: text("job_type").notNull(),
  input: jsonb("input").notNull(),
  status: text("status").default("PENDING").notNull(),
  priority: smallint("priority").default(50).notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  retryCount: integer("retry_count").default(0).notNull(),
  nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true, mode: 'date' }),
}, (table) => [
  unique("job_generated_uq_0").on(table.organizationId, table.idempotencyKey),
]);

export const execution = rhia.table("execution", {
  id: uuid("id").primaryKey().defaultRandom(),
  jobId: uuid("job_id").notNull().references(() => job.id),
  attempt: integer("attempt").notNull(),
  executorType: text("executor_type").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  endedAt: timestamp("ended_at", { withTimezone: true, mode: 'date' }),
  outcome: text("outcome"),
  errorCode: text("error_code"),
  traceId: uuid("trace_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("execution_generated_uq_0").on(table.jobId, table.attempt),
]);

export const action = rhia.table("action", {
  id: uuid("id").primaryKey().defaultRandom(),
  executionId: uuid("execution_id").notNull().references(() => execution.id),
  capabilityKey: text("capability_key").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: uuid("resource_id"),
  requestPayload: jsonb("request_payload").default({}).notNull(),
  responseSummary: jsonb("response_summary"),
  riskLevel: text("risk_level").notNull(),
  status: text("status").default("PENDING").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const approval = rhia.table("approval", {
  id: uuid("id").primaryKey().defaultRandom(),
  actionId: uuid("action_id").notNull().references(() => action.id),
  requestedByAgentInstanceId: uuid("requested_by_agent_instance_id").references(() => agentInstance.id),
  approvalType: text("approval_type").notNull(),
  status: text("status").default("PENDING").notNull(),
  approverUserId: uuid("approver_user_id").references(() => appUser.id),
  reason: text("reason"),
  requestedAt: timestamp("requested_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  decidedAt: timestamp("decided_at", { withTimezone: true, mode: 'date' }),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const companyGroup = rhia.table("company_group", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  canonicalName: text("canonical_name").notNull(),
  websiteRoot: text("website_root"),
  globalIdentityStatus: text("global_identity_status").default("UNRESOLVED").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const companyEntity = rhia.table("company_entity", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  companyGroupId: uuid("company_group_id").notNull().references(() => companyGroup.id),
  legalName: text("legal_name").notNull(),
  tradeName: text("trade_name"),
  countryCode: char("country_code", { length: 2 }).notNull(),
  legalIdentifier: text("legal_identifier"),
  entityType: text("entity_type").notNull(),
  status: text("status").default("ACTIVE").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const companyLocation = rhia.table("company_location", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  companyEntityId: uuid("company_entity_id").notNull().references(() => companyEntity.id),
  countryCode: char("country_code", { length: 2 }).notNull(),
  administrativeArea: text("administrative_area"),
  city: text("city").notNull(),
  address: text("address"),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  timezone: text("timezone"),
  isHeadquarters: boolean("is_headquarters").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const companyAlias = rhia.table("company_alias", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  companyGroupId: uuid("company_group_id").references(() => companyGroup.id),
  companyEntityId: uuid("company_entity_id").references(() => companyEntity.id),
  alias: text("alias").notNull(),
  source: text("source").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const evidenceSource = rhia.table("evidence_source", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  sourceType: text("source_type").notNull(),
  domain: text("domain"),
  url: text("url").notNull(),
  fetchedAt: timestamp("fetched_at", { withTimezone: true, mode: 'date' }).notNull(),
  provider: text("provider").notNull(),
  sourceReliability: numeric("source_reliability", { precision: 5, scale: 4 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const evidence = rhia.table("evidence", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  subjectType: text("subject_type").notNull(),
  subjectId: uuid("subject_id").notNull(),
  sourceId: uuid("source_id").notNull().references(() => evidenceSource.id),
  claimType: text("claim_type").notNull(),
  excerptHash: char("excerpt_hash", { length: 64 }).notNull(),
  observedValue: jsonb("observed_value").notNull(),
  confidence: numeric("confidence", { precision: 5, scale: 4 }).notNull(),
  freshnessAt: timestamp("freshness_at", { withTimezone: true, mode: 'date' }).notNull(),
  status: text("status").default("ACTIVE").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const fact = rhia.table("fact", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  subjectType: text("subject_type").notNull(),
  subjectId: uuid("subject_id").notNull(),
  predicate: text("predicate").notNull(),
  value: jsonb("value").notNull(),
  confidence: numeric("confidence", { precision: 5, scale: 4 }).notNull(),
  validFrom: timestamp("valid_from", { withTimezone: true, mode: 'date' }),
  validTo: timestamp("valid_to", { withTimezone: true, mode: 'date' }),
  supportingEvidenceIds: uuid("supporting_evidence_ids").array().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const modelProvider = rhia.table("model_provider", {
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  provider: text("provider").notNull(),
  status: text("status").default("INACTIVE").notNull(),
  capabilities: jsonb("capabilities").default([]).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.organizationId, table.provider] }),
]);

export const modelProfile = rhia.table("model_profile", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  taskClass: text("task_class").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  qualityScore: numeric("quality_score", { precision: 6, scale: 3 }).default("0").notNull(),
  latencyScore: numeric("latency_score", { precision: 6, scale: 3 }).default("0").notNull(),
  costScore: numeric("cost_score", { precision: 6, scale: 3 }).default("0").notNull(),
  privacyClass: text("privacy_class").notNull(),
  enabled: boolean("enabled").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  foreignKey({ columns: [table.organizationId, table.provider], foreignColumns: [modelProvider.organizationId, modelProvider.provider] }),
  unique("model_profile_generated_uq_0").on(table.organizationId, table.taskClass, table.provider, table.model),
]);

export const modelRun = rhia.table("model_run", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  jobId: uuid("job_id").references(() => job.id),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  taskClass: text("task_class").notNull(),
  inputTokens: integer("input_tokens").default(0).notNull(),
  outputTokens: integer("output_tokens").default(0).notNull(),
  estimatedCost: numeric("estimated_cost", { precision: 14, scale: 6 }).default("0").notNull(),
  latencyMs: integer("latency_ms").default(0).notNull(),
  success: boolean("success").notNull(),
  qualityResult: jsonb("quality_result"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const inference = rhia.table("inference", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  subjectType: text("subject_type").notNull(),
  subjectId: uuid("subject_id").notNull(),
  inferenceType: text("inference_type").notNull(),
  value: jsonb("value").notNull(),
  confidence: numeric("confidence", { precision: 5, scale: 4 }).notNull(),
  modelRunId: uuid("model_run_id").notNull().references(() => modelRun.id),
  supportingFactIds: uuid("supporting_fact_ids").array().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const decisionRecord = rhia.table("decision_record", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  decisionType: text("decision_type").notNull(),
  inputSnapshot: jsonb("input_snapshot").notNull(),
  output: jsonb("output").notNull(),
  rationaleSummary: text("rationale_summary").notNull(),
  policyVersion: text("policy_version").notNull(),
  modelRunId: uuid("model_run_id").references(() => modelRun.id),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const contact = rhia.table("contact", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  companyGroupId: uuid("company_group_id").notNull().references(() => companyGroup.id),
  companyEntityId: uuid("company_entity_id").references(() => companyEntity.id),
  fullName: text("full_name").notNull(),
  title: text("title"),
  department: text("department"),
  seniority: text("seniority"),
  countryCode: char("country_code", { length: 2 }),
  city: text("city"),
  linkedinUrl: text("linkedin_url"),
  status: text("status").default("UNVERIFIED").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const contactPoint = rhia.table("contact_point", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  contactId: uuid("contact_id").notNull().references(() => contact.id),
  pointType: text("point_type").notNull(),
  valueEncrypted: bytea("value_encrypted").notNull(),
  valueHash: char("value_hash", { length: 64 }).notNull(),
  validationStatus: text("validation_status").default("UNVERIFIED").notNull(),
  sourceId: uuid("source_id").references(() => evidenceSource.id),
  lastValidatedAt: timestamp("last_validated_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const opportunity = rhia.table("opportunity", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  companyGroupId: uuid("company_group_id").notNull().references(() => companyGroup.id),
  primaryEntityId: uuid("primary_entity_id").references(() => companyEntity.id),
  marketCountry: char("market_country", { length: 2 }).notNull(),
  marketCity: text("market_city"),
  stage: text("stage").notNull(),
  score: numeric("score", { precision: 6, scale: 3 }).default("0").notNull(),
  scoreVersion: text("score_version").notNull(),
  ownerUserId: uuid("owner_user_id").references(() => appUser.id),
  nextActionAt: timestamp("next_action_at", { withTimezone: true, mode: 'date' }),
  status: text("status").default("OPEN").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const opportunitySignal = rhia.table("opportunity_signal", {
  id: uuid("id").primaryKey().defaultRandom(),
  opportunityId: uuid("opportunity_id").notNull().references(() => opportunity.id),
  signalType: text("signal_type").notNull(),
  signalValue: jsonb("signal_value").notNull(),
  evidenceId: uuid("evidence_id").notNull().references(() => evidence.id),
  weight: numeric("weight", { precision: 8, scale: 4 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const product = rhia.table("product", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  sku: text("sku").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  active: boolean("active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("product_generated_uq_0").on(table.organizationId, table.sku),
]);

export const priceBook = rhia.table("price_book", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  countryCode: char("country_code", { length: 2 }).notNull(),
  currency: char("currency", { length: 3 }).notNull(),
  validFrom: timestamp("valid_from", { withTimezone: true, mode: 'date' }).notNull(),
  validTo: timestamp("valid_to", { withTimezone: true, mode: 'date' }),
  status: text("status").default("DRAFT").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const priceBookItem = rhia.table("price_book_item", {
  priceBookId: uuid("price_book_id").notNull().references(() => priceBook.id),
  productId: uuid("product_id").notNull().references(() => product.id),
  unitPrice: numeric("unit_price", { precision: 14, scale: 4 }).notNull(),
  minimumQuantity: numeric("minimum_quantity", { precision: 14, scale: 4 }).default("1").notNull(),
  policyMetadata: jsonb("policy_metadata").default({}).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.priceBookId, table.productId] }),
]);

export const outreachSequence = rhia.table("outreach_sequence", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  opportunityId: uuid("opportunity_id").notNull().references(() => opportunity.id),
  policyId: uuid("policy_id"),
  status: text("status").default("DRAFT").notNull(),
  maxTouches: smallint("max_touches").default(3).notNull(),
  timezone: text("timezone").notNull(),
  quietHours: jsonb("quiet_hours").default({}).notNull(),
  startedAt: timestamp("started_at", { withTimezone: true, mode: 'date' }),
  stoppedAt: timestamp("stopped_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const outreachTouch = rhia.table("outreach_touch", {
  id: uuid("id").primaryKey().defaultRandom(),
  sequenceId: uuid("sequence_id").notNull().references(() => outreachSequence.id),
  contactId: uuid("contact_id").notNull().references(() => contact.id),
  channel: text("channel").notNull(),
  plannedAt: timestamp("planned_at", { withTimezone: true, mode: 'date' }).notNull(),
  sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }),
  status: text("status").default("PLANNED").notNull(),
  messageVersion: text("message_version").notNull(),
  providerMessageId: text("provider_message_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("outreach_touch_generated_uq_0").on(table.sequenceId, table.idempotencyKey),
]);

export const conversation = rhia.table("conversation", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  opportunityId: uuid("opportunity_id").notNull().references(() => opportunity.id),
  contactId: uuid("contact_id").notNull().references(() => contact.id),
  channel: text("channel").notNull(),
  status: text("status").notNull(),
  sentiment: text("sentiment"),
  intent: text("intent"),
  lastMessageAt: timestamp("last_message_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const message = rhia.table("message", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id").notNull().references(() => conversation.id),
  direction: text("direction").notNull(),
  contentRedacted: text("content_redacted").notNull(),
  providerMessageId: text("provider_message_id"),
  sentAt: timestamp("sent_at", { withTimezone: true, mode: 'date' }).notNull(),
  detectedIntent: text("detected_intent"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const meeting = rhia.table("meeting", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  opportunityId: uuid("opportunity_id").notNull().references(() => opportunity.id),
  contactId: uuid("contact_id").notNull().references(() => contact.id),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true, mode: 'date' }).notNull(),
  timezone: text("timezone").notNull(),
  status: text("status").notNull(),
  qualificationStatus: text("qualification_status").default("UNQUALIFIED").notNull(),
  attended: boolean("attended").default(false).notNull(),
  outcome: text("outcome"),
  calendarEventId: text("calendar_event_id"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const modelBenchmark = rhia.table("model_benchmark", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  taskClass: text("task_class").notNull(),
  datasetVersion: text("dataset_version").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  accuracy: numeric("accuracy", { precision: 6, scale: 5 }).notNull(),
  costPerCase: numeric("cost_per_case", { precision: 14, scale: 6 }).notNull(),
  latencyP50: integer("latency_p50").notNull(),
  latencyP95: integer("latency_p95").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("model_benchmark_generated_uq_0").on(table.organizationId, table.taskClass, table.datasetVersion, table.provider, table.model),
]);

export const auditEvent = rhia.table("audit_event", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  actorRef: uuid("actor_ref"),
  actorType: text("actor_type").notNull(),
  action: text("action").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: uuid("resource_id"),
  beforeHash: char("before_hash", { length: 64 }),
  afterHash: char("after_hash", { length: 64 }),
  occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  traceId: uuid("trace_id").notNull(),
}, (table) => [
]);

export const systemHealthEvent = rhia.table("system_health_event", {
  id: uuid("id").primaryKey().defaultRandom(),
  component: text("component").notNull(),
  status: text("status").notNull(),
  detail: jsonb("detail").default({}).notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const legacyObjectMap = rhia.table("legacy_object_map", {
  id: uuid("id").primaryKey().defaultRandom(),
  sourceTable: text("source_table").notNull(),
  sourceKey: text("source_key").notNull(),
  targetTable: text("target_table").notNull(),
  targetId: uuid("target_id").notNull(),
  migrationVersion: text("migration_version").notNull(),
  migratedAt: timestamp("migrated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("legacy_object_map_generated_uq_0").on(table.sourceTable, table.sourceKey, table.targetTable),
]);

export const outreachPolicy = rhia.table("outreach_policy", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  version: text("version").notNull(),
  name: text("name").notNull(),
  configuration: jsonb("configuration").notNull(),
  status: text("status").default("DRAFT").notNull(),
  approvedByUserId: uuid("approved_by_user_id").references(() => appUser.id),
  approvedAt: timestamp("approved_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("outreach_policy_generated_uq_0").on(table.organizationId, table.version),
]);

export const outreachSuppression = rhia.table("outreach_suppression", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  subjectType: text("subject_type").notNull(),
  subjectKeyHash: char("subject_key_hash", { length: 64 }).notNull(),
  reason: text("reason").notNull(),
  source: text("source").notNull(),
  active: boolean("active").default(true).notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const coreIdempotency = rhia.table("core_idempotency", {
  organizationId: uuid("organization_id").notNull().references(() => organization.id),
  operation: text("operation").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  fingerprint: char("fingerprint", { length: 64 }).notNull(),
  resourceType: text("resource_type").notNull(),
  resourceId: uuid("resource_id").notNull(),
  resourceSnapshot: jsonb("resource_snapshot").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ columns: [table.organizationId, table.operation, table.idempotencyKey] }),
]);

export const authUser = rhia.table("auth_user", {
  id: uuid("id").primaryKey().defaultRandom(),
  appUserId: uuid("app_user_id").notNull().unique().references(() => appUser.id),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const authSession = rhia.table("auth_session", {
  id: uuid("id").primaryKey().defaultRandom(),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: uuid("user_id").notNull().references(() => authUser.id),
}, (table) => [
]);

export const authAccount = rhia.table("auth_account", {
  id: uuid("id").primaryKey().defaultRandom(),
  issuer: text("issuer").notNull(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: uuid("user_id").notNull().references(() => authUser.id),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true, mode: 'date' }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true, mode: 'date' }),
  scope: text("scope"),
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
  unique("auth_account_generated_uq_0").on(table.issuer, table.accountId),
]);

export const authVerification = rhia.table("auth_verification", {
  id: uuid("id").primaryKey().defaultRandom(),
  identifierHash: text("identifier_hash").notNull(),
  valueHash: text("value_hash").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'date' }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
}, (table) => [
]);

export const authRateLimit = rhia.table("auth_rate_limit", {
  id: uuid("id").primaryKey().defaultRandom(),
  keyHash: text("key_hash").notNull().unique(),
  count: integer("count").notNull(),
  lastRequestAtMs: bigint("last_request_at_ms", { mode: 'number' }).notNull(),
}, (table) => [
]);
